set(CMAKE_C_COMPILER gcc CACHE STRING "C Compiler")
set(CMAKE_CXX_COMPILER g++ CACHE STRING "CXX Compiler")
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER} CACHE STRING "ASM Compiler")

find_program(CMAKE_C_COMPILER_PATH_EXE ${CMAKE_C_COMPILER} REQUIRED)
get_filename_component(CMAKE_C_COMPILER_PATH_BIN ${CMAKE_C_COMPILER_PATH_EXE} DIRECTORY)
get_filename_component(CMAKE_C_COMPILER_PATH_ROOT ${CMAKE_C_COMPILER_PATH_BIN} DIRECTORY)
message(STATUS "CMAKE_C_COMPILER_PATH_ROOT: ${CMAKE_C_COMPILER_PATH_ROOT}")

include_directories(BEFORE ${CMAKE_C_COMPILER_PATH_ROOT}/x86_64-w64-mingw32/include)
