pipeline:
  - step: CreateVEnv
    module: pypeline.steps.create_venv
    config:
      bootstrap_script: .bootstrap/bootstrap.py
      python_executable: python311
  - step: ScoopInstall
    module: pypeline.steps.scoop_install
  - step: GenerateEnvSetupScript
    module: pypeline.steps.env_setup_script
  - step: CheckCIContext
    module: pypeline_semantic_release.steps
  - step: CollectPRChanges
    module: spl_core.steps.collect_pr_changes
