[project]
name = "spled"
version = "0.0.1"
description = "SPL demo project"
authors = [{ name = "Avengineers" }]
requires-python = "<3.12,>=3.11"

dependencies = [
    "spl-core (==8.2.0rc5)",
    "clanguru>=0.20,<1",
    "pypeline-runner>=1.29,<2",
    "pytest>=8,<9",
    "myst-parser>=4.0,<5",
    "pypeline-semantic-release>=0,<1",
    "poks>=0.9.4,<1"
]

[tool.poetry]
package-mode = false

[tool.ruff]
line-length = 180
