[pytest]
pythonpath =
    "test"
testpaths =
    "test"
junit_logging = all
addopts =
    --capture=tee-sys
    -vv
markers =
    just_a_try: mark a test as a try
    unittests: tests of individual units of code
    reports: tests of the report generation
    build_debug: tests of the target builds with build type debug
    build_release: tests of the target builds with build type release
    static_analysis: tests of static code analysis
