from pathlib import Path
from typing import List

from yanga.domain.execution_context import (
    ExecutionContext,
)

from yanga.cmake.cmake_backend import (
    CMakeComment,
    CMakeElement,
)
from yanga.cmake.generator import CMakeGenerator


class SplCMakeGenerator(CMakeGenerator):
    """Generates CMake elements to build an executable for a variant."""

    def __init__(self, execution_context: ExecutionContext, output_dir: Path) -> None:
        super().__init__(execution_context, output_dir)

    def generate(self) -> List[CMakeElement]:
        elements: List[CMakeElement] = []
        elements.append(CMakeComment(f"Generated by {self.__class__.__name__}"))
        return elements
